apiVersion: apps/v1
kind: Deployment
metadata:
 name: nodejs-app
spec:
  replicas: 3
  selector:
	matchLabels:
  	app: nodejs-app
  template:
	metadata:
  	labels:
    	app: nodejs-app
	spec:
  	containers:
  	- name: nodejs-container
    	image: katline/redis-node
    	ports:
    	- containerPort: 5400
---
apiVersion: v1
kind: Service
metadata:
 name: nodejs-service
spec:
  selector:
	app: nodejs-app
  ports:
  - protocol: TCP
	port: 80
	targetPort: 5400
  type: LoadBalancer
